on:
  push:
    branches:
      - main

jobs:
  build-with-docker-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 10.7.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - name: "Install Dependencies"
        run: pnpm install
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: "Build and push images"
        env:
          INPUT_PUSH: "true"
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpx nx affected --target=container --parallel=2
